# Generated by Django 3.2.15 on 2022-08-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('member_name', models.CharField(max_length=250, null=True)),
                ('date_of_service', models.DateTimeField()),
                ('medicaid_id', models.IntegerField(blank=True, null=True)),
                ('mobile_no', models.CharField(max_length=250, null=True)),
                ('pa_name', models.CharField(default=None, max_length=250, null=True)),
                ('employee_id', models.IntegerField(blank=True, default=None, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('password', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.CharField(blank=True, max_length=250, null=True)),
                ('is_admin', models.BooleanField(blank=True, default=True, null=True)),
                ('is_employee', models.BooleanField(blank=True, default=True, null=True)),
                ('created_by', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_by', models.CharField(max_length=100, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
