# Generated by Django 3.2.15 on 2022-08-28 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='member_name',
            new_name='employee_name',
        ),
    ]
