# Generated by Django 3.2.15 on 2022-08-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_name', models.CharField(max_length=50)),
                ('medicaid_id', models.IntegerField()),
                ('date_of_service', models.DateTimeField()),
                ('pa_name', models.CharField(max_length=50)),
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mobile_no', models.CharField(max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=30, null=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
