# Generated by Django 3.2.15 on 2022-08-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demouser',
            name='id',
        ),
        migrations.AlterField(
            model_name='demouser',
            name='employee_id',
            field=models.IntegerField(blank=True, default=None, primary_key=True, serialize=False),
        ),
    ]
