# Generated by Django 3.2.15 on 2022-08-16 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0002_demographics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demographics',
            old_name='employee_id',
            new_name='employee',
        ),
        migrations.CreateModel(
            name='HoursAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_day', models.BooleanField(default=True)),
                ('is_night', models.BooleanField(default=True)),
                ('is_live_in', models.BooleanField(default=True)),
                ('is_saturday', models.BooleanField(default=True)),
                ('is_sunday', models.BooleanField(default=True)),
                ('is_monday', models.BooleanField(default=True)),
                ('is_tuesday', models.BooleanField(default=True)),
                ('is_wednesday', models.BooleanField(default=True)),
                ('is_thursday', models.BooleanField(default=True)),
                ('is_friday', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_app.employee')),
            ],
        ),
    ]
