# Generated by Django 3.2.15 on 2022-08-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0002_auto_20220821_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='demouser',
            name='email',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='demouser',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='demouser',
            name='password',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
