# Generated by Django 3.2.15 on 2022-08-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0003_auto_20220821_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='date_of_service',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.IntegerField(blank=True, default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='medicaid_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pa_name',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
