# Generated by Django 3.2.15 on 2022-08-16 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0004_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_school_city_state', models.CharField(max_length=350)),
                ('entrance_date', models.DateTimeField(auto_now_add=True)),
                ('is_graduate', models.BooleanField(default=True)),
                ('certificate_degree', models.CharField(max_length=250)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_app.employee')),
            ],
        ),
    ]
