# Generated by Django 3.2.15 on 2022-08-16 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0005_professionaltraining'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills_Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_home_care', models.BooleanField(default=True)),
                ('is_denture_care', models.BooleanField(default=True)),
                ('is_non_sterile_dressing', models.BooleanField(default=True)),
                ('is_orthopedics', models.BooleanField(default=True)),
                ('is_special_diets', models.BooleanField(default=True)),
                ('is_range_of_motion', models.BooleanField(default=True)),
                ('is_vital_signs', models.BooleanField(default=True)),
                ('is_diabetes_care', models.BooleanField(default=True)),
                ('is_kosher_cooking', models.BooleanField(default=True)),
                ('is_transfer_techniques', models.BooleanField(default=True)),
                ('is_urine_testing', models.BooleanField(default=True)),
                ('is_patient_teaching', models.BooleanField(default=True)),
                ('is_household_maintenance', models.BooleanField(default=True)),
                ('is_hoyer_lift', models.BooleanField(default=True)),
                ('is_geriatrics', models.BooleanField(default=True)),
                ('other1', models.CharField(max_length=400)),
                ('is_laundry', models.BooleanField(default=True)),
                ('is_foyer_lift', models.BooleanField(default=True)),
                ('is_child_care', models.BooleanField(default=True)),
                ('other2', models.CharField(max_length=400)),
                ('is_bed_bath', models.BooleanField(default=True)),
                ('is_ostomy_care', models.BooleanField(default=True)),
                ('is_newborn_care', models.BooleanField(default=True)),
                ('other3', models.CharField(max_length=400)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_app.employee')),
            ],
        ),
    ]
