# Generated by Django 3.2.15 on 2022-08-21 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0005_rename_date_employee_date_of_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='signature',
        ),
    ]
