# Generated by Django 3.2.15 on 2022-08-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0006_remove_employee_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
