# Generated by Django 3.2.15 on 2022-08-16 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0006_skills_checklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_bus_train_car', models.BooleanField(default=True)),
                ('routes', models.CharField(max_length=500)),
                ('is_valid_licenses', models.BooleanField(default=True)),
                ('is_permission_for_criminal_background', models.BooleanField(default=True)),
                ('is_personal_assistant_guide', models.BooleanField(default=True)),
                ('printed_name', models.CharField(max_length=250)),
                ('signature_img', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_app.employee')),
            ],
        ),
    ]
