# Generated by Django 3.2.15 on 2022-08-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0007_alter_employee_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acknowledgementofreceipt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='acknowledgementofreceipt',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='acknowledgementofreceipt',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agreementwithcompany',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='agreementwithcompany',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agreementwithcompany',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='authorizationbackgroundcheck',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='authorizationbackgroundcheck',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='authorizationbackgroundcheck',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='benefitportioncompensation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='benefitportioncompensation',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='benefitportioncompensation',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demouser',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depositauthorization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='depositauthorization',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='depositauthorization',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disclosuredrugtesting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='disclosuredrugtesting',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='disclosuredrugtesting',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drugtestguidelines',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='drugtestguidelines',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drugtestguidelines',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeacknowledgement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeacknowledgement',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeacknowledgement',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeinformationattestation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeinformationattestation',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeinformationattestation',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeewithholdingallowancecertificate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeewithholdingallowancecertificate',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeewithholdingallowancecertificate',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeewithholdingcertificate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeewithholdingcertificate',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeewithholdingcertificate',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employerinformation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='employerinformation',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employerinformation',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employerreviewverification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='employerreviewverification',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employerreviewverification',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employmentfirstday',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='employmentfirstday',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employmentfirstday',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hoursavailable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='hoursavailable',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hoursavailable',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='noticeacknowledgement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='noticeacknowledgement',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='noticeacknowledgement',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professionaltraining',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='professionaltraining',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='professionaltraining',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reverificationrehires',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='reverificationrehires',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reverificationrehires',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skillschecklist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='skillschecklist',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skillschecklist',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='translatorcertificate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='translatorcertificate',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='translatorcertificate',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voluntaryidentification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='voluntaryidentification',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='voluntaryidentification',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
