# Generated by Django 3.2.15 on 2022-08-16 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0007_transportation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeWithholdingCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_middle_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('social_security_number', models.IntegerField()),
                ('address', models.CharField(max_length=500, null=True)),
                ('city_town_state_zip', models.CharField(max_length=500, null=True)),
                ('is_single_or_married', models.BooleanField(default=True)),
                ('is_married_jointly', models.BooleanField(default=True)),
                ('is_head_of_household', models.BooleanField(default=True)),
                ('is_two_jobs_total', models.BooleanField(default=True)),
                ('children_under_age', models.IntegerField()),
                ('others_dependents', models.IntegerField()),
                ('total', models.IntegerField()),
                ('other_income', models.IntegerField()),
                ('deductions', models.IntegerField()),
                ('extra_withholding', models.IntegerField()),
                ('employee_signature_img', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('employer_name_address', models.CharField(max_length=500, null=True)),
                ('first_date_of_employment', models.DateTimeField(auto_now_add=True, null=True)),
                ('employer_identification_no', models.IntegerField()),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_app.employee')),
            ],
        ),
    ]
