# Generated by Django 3.2.15 on 2022-08-16 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0008_employeewithholdingcertificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeWithholdingAllowanceCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_middle_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('social_security_number', models.IntegerField()),
                ('permanent_home_address', models.CharField(max_length=500, null=True)),
                ('apartment_no', models.IntegerField()),
                ('city_village_post_office', models.CharField(max_length=500, null=True)),
                ('state', models.CharField(max_length=300, null=True)),
                ('zip_code', models.IntegerField()),
                ('is_single_or_head_of_household', models.BooleanField(default=True)),
                ('is_married', models.BooleanField(default=True)),
                ('is_married_higher_single_rate', models.BooleanField(default=True)),
                ('is_new_york_resident', models.BooleanField(default=True)),
                ('is_yonkers_resident', models.BooleanField(default=True)),
                ('total_newyork_yonkers_allowance', models.IntegerField()),
                ('total_newyork_allowance', models.IntegerField()),
                ('new_york_state_amount', models.IntegerField()),
                ('new_york_city_amount', models.IntegerField()),
                ('yonkers_amount', models.IntegerField()),
                ('employee_signature_img', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_exemption_allowances', models.BooleanField(default=True)),
                ('is_new_hire', models.BooleanField(default=True)),
                ('employee_performed_date', models.DateTimeField(auto_now_add=True)),
                ('is_health_insurance', models.BooleanField(default=True)),
                ('employee_qualifies_date', models.DateTimeField(auto_now_add=True)),
                ('employer_name_address', models.CharField(max_length=600, null=True)),
                ('employer_identification_no', models.IntegerField()),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_app.employee')),
            ],
        ),
    ]
