# Generated by Django 3.2.15 on 2022-08-16 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0010_employeeinformationattestation_employerreviewverification_translatorcertificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReverificationRehires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('middle_name', models.CharField(max_length=150, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('date_of_rehire', models.DateTimeField(auto_now_add=True)),
                ('document_title', models.CharField(max_length=150, null=True)),
                ('document_no', models.CharField(max_length=150, null=True)),
                ('expire_date', models.DateTimeField(auto_now_add=True)),
                ('employee_signature_img', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('today_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('employer_name', models.CharField(max_length=150, null=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentFirstDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_signature_img', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('today_date', models.DateTimeField(auto_now_add=True)),
                ('employer_title', models.CharField(max_length=200)),
                ('employer_first_name', models.CharField(max_length=200, null=True)),
                ('employer_last_name', models.CharField(max_length=200, null=True)),
                ('business_organization_name', models.CharField(max_length=800, null=True)),
                ('business_organization_address', models.CharField(max_length=1000, null=True)),
                ('city_town', models.CharField(max_length=500, null=True)),
                ('state', models.CharField(max_length=500, null=True)),
                ('zip_code', models.IntegerField()),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_app.employee')),
            ],
        ),
    ]
