# Generated by Django 3.2.15 on 2022-08-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0011_alter_demographics_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoursavailable',
            name='is_day',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hoursavailable',
            name='is_friday',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hoursavailable',
            name='is_live_in',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hoursavailable',
            name='is_monday',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hoursavailable',
            name='is_night',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hoursavailable',
            name='is_saturday',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hoursavailable',
            name='is_sunday',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hoursavailable',
            name='is_thursday',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hoursavailable',
            name='is_tuesday',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hoursavailable',
            name='is_wednesday',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
