# Generated by Django 3.2.15 on 2022-08-16 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0012_acknowledgementofreceipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoluntaryIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('business_unit_location', models.CharField(max_length=600)),
                ('department', models.CharField(max_length=500)),
                ('job_title_position', models.CharField(max_length=400)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_male', models.BooleanField(default=True)),
                ('is_female', models.BooleanField(default=True)),
                ('is_disclose_sex', models.BooleanField(default=True)),
                ('is_hispanic_or_latino', models.BooleanField(default=True)),
                ('is_middle_or_north_east', models.BooleanField(default=True)),
                ('is_black_or_african_American', models.BooleanField(default=True)),
                ('is_other_pacific_island', models.BooleanField(default=True)),
                ('is_asian', models.BooleanField(default=True)),
                ('is_american_indian_or_alaskan', models.BooleanField(default=True)),
                ('is_two_or_more_races', models.BooleanField(default=True)),
                ('is_disclose_info', models.BooleanField(default=True)),
                ('is_disabled_veteran', models.BooleanField(default=True)),
                ('date_of_active_duty', models.DateTimeField(auto_now_add=True)),
                ('is_armed_forces', models.BooleanField(default=True)),
                ('is_other_protected_veteran', models.BooleanField(default=True)),
                ('military_discharge_date', models.DateTimeField(auto_now_add=True)),
                ('is_disclose_military_status', models.BooleanField(default=True)),
                ('is_no_military_status', models.BooleanField(default=True)),
                ('is_have_disability', models.BooleanField(default=True)),
                ('is_no_disability', models.BooleanField(default=True)),
                ('is_disclose_disability', models.BooleanField(default=True)),
                ('nature_of_disability', models.CharField(max_length=800)),
                ('voluntarily_info', models.CharField(max_length=1000)),
                ('employee_signature_img', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('sign_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_app.employee')),
            ],
        ),
    ]
