# Generated by Django 3.2.15 on 2022-08-16 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0013_voluntaryidentification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationBackgroundCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_printed_name', models.CharField(max_length=200)),
                ('employee_signature_img', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='AgreementWithCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_printed_name', models.CharField(max_length=100)),
                ('employee_signature_img', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_app.employee')),
            ],
        ),
    ]
