# Generated by Django 3.2.15 on 2022-08-21 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0013_alter_hoursavailable_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='college',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='college_city_state',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='employee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education', to='employee_app.employee'),
        ),
        migrations.AlterField(
            model_name='education',
            name='high_school_city_state',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='high_school_name',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
