# Generated by Django 3.2.15 on 2022-08-23 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0014_auto_20220821_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionaltraining',
            name='certificate_degree',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='professionaltraining',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professionaltraining', to='employee_app.employee'),
        ),
        migrations.AlterField(
            model_name='professionaltraining',
            name='entrance_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='professionaltraining',
            name='is_graduate',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='professionaltraining',
            name='name_of_school_city_state',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
