# Generated by Django 3.2.15 on 2022-08-16 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0015_disclosuredrugtesting_drugtestguidelines_employerinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_at_hiring', models.BooleanField(default=True)),
                ('is_before_change', models.BooleanField(default=True)),
                ('employee_rates', models.IntegerField()),
                ('wage_parity_rates', models.IntegerField()),
                ('is_none', models.BooleanField(default=True)),
                ('tips', models.IntegerField()),
                ('meals', models.IntegerField()),
                ('loading', models.CharField(max_length=200)),
                ('allowance_other', models.CharField(max_length=200)),
                ('regular_payday', models.CharField(max_length=200)),
                ('is_weekly', models.BooleanField(default=True)),
                ('is_bi_weekly', models.BooleanField(default=True)),
                ('pay_other', models.CharField(max_length=200)),
                ('single_pay_rate', models.IntegerField()),
                ('wage_parity_pay_rates', models.IntegerField()),
                ('multiple_pay_rates', models.IntegerField()),
                ('is_notice_in_english', models.BooleanField(default=True)),
                ('primary_language', models.CharField(max_length=100)),
                ('employee_printed_name', models.CharField(max_length=100)),
                ('employee_signature_img', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('papers_name_title', models.CharField(max_length=200)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_language', models.CharField(max_length=250)),
                ('is_notice_given', models.BooleanField(default=True)),
                ('employee_printed_name', models.CharField(max_length=200)),
                ('employee_signature_img', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('sign_date', models.DateTimeField(auto_now_add=True)),
                ('papers_name_title', models.CharField(max_length=500)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='DepositAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=800)),
                ('city_state_zip', models.CharField(max_length=600)),
                ('name_of_bank', models.CharField(max_length=500)),
                ('account', models.IntegerField()),
                ('digit_routing', models.IntegerField()),
                ('is_checking', models.BooleanField(default=True)),
                ('is_savings', models.BooleanField(default=True)),
                ('employee_signature_img', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='BenefitPortionCompensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.IntegerField()),
                ('type_of_supplement', models.CharField(max_length=500)),
                ('provider_name_address', models.CharField(max_length=800)),
                ('agreement_info', models.CharField(max_length=1000)),
                ('obtained_by', models.CharField(max_length=400)),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.CharField(max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_app.employee')),
            ],
        ),
    ]
