# Generated by Django 3.2.15 on 2022-08-19 17:04

from django.db import migrations
import jsignature.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0016_benefitportioncompensation_depositauthorization_employeeacknowledgement_noticeacknowledgement'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='signature',
            field=jsignature.fields.JSignatureField(default=None),
        ),
    ]
