# Generated by Django 3.2.15 on 2022-08-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0017_auto_20220823_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillschecklist',
            name='other1',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='skillschecklist',
            name='other2',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='skillschecklist',
            name='other3',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
