# Generated by Django 3.2.15 on 2022-08-23 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0018_auto_20220823_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillschecklist',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skillschecklist', to='employee_app.employee'),
        ),
    ]
