# Generated by Django 3.2.15 on 2022-08-20 04:49

from django.db import migrations, models
import jsignature.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0019_alter_signaturemodel_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('signature', jsignature.fields.JSignatureField(default=None)),
            ],
        ),
    ]
