# Generated by Django 3.2.15 on 2022-08-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0021_auto_20220823_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeewithholdingcertificate',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='employeewithholdingcertificate',
            name='children_under_age',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='employeewithholdingcertificate',
            name='city_town_state_zip',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='employeewithholdingcertificate',
            name='deductions',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='employeewithholdingcertificate',
            name='employer_identification_no',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='employeewithholdingcertificate',
            name='employer_name_address',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='employeewithholdingcertificate',
            name='extra_withholding',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='employeewithholdingcertificate',
            name='first_middle_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employeewithholdingcertificate',
            name='is_head_of_household',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='employeewithholdingcertificate',
            name='is_married_jointly',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='employeewithholdingcertificate',
            name='is_single_or_married',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='employeewithholdingcertificate',
            name='is_two_jobs_total',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='employeewithholdingcertificate',
            name='last_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employeewithholdingcertificate',
            name='other_income',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='employeewithholdingcertificate',
            name='others_dependents',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='employeewithholdingcertificate',
            name='social_security_number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='employeewithholdingcertificate',
            name='total',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
