# Generated by Django 3.2.15 on 2022-08-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0022_auto_20220824_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeewithholdingallowancecertificate',
            name='apartment_no',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='employeewithholdingallowancecertificate',
            name='city_village_post_office',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='employeewithholdingallowancecertificate',
            name='employer_name_address',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='employeewithholdingallowancecertificate',
            name='first_middle_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employeewithholdingallowancecertificate',
            name='is_exemption_allowances',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='employeewithholdingallowancecertificate',
            name='is_health_insurance',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='employeewithholdingallowancecertificate',
            name='is_married',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='employeewithholdingallowancecertificate',
            name='is_married_higher_single_rate',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='employeewithholdingallowancecertificate',
            name='is_new_hire',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='employeewithholdingallowancecertificate',
            name='is_new_york_resident',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='employeewithholdingallowancecertificate',
            name='is_single_or_head_of_household',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='employeewithholdingallowancecertificate',
            name='is_yonkers_resident',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='employeewithholdingallowancecertificate',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employeewithholdingallowancecertificate',
            name='new_york_city_amount',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='employeewithholdingallowancecertificate',
            name='new_york_state_amount',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='employeewithholdingallowancecertificate',
            name='permanent_home_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='employeewithholdingallowancecertificate',
            name='social_security_number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='employeewithholdingallowancecertificate',
            name='state',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='employeewithholdingallowancecertificate',
            name='total_newyork_allowance',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='employeewithholdingallowancecertificate',
            name='total_newyork_yonkers_allowance',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='employeewithholdingallowancecertificate',
            name='yonkers_amount',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='employeewithholdingallowancecertificate',
            name='zip_code',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
