# Generated by Django 3.2.15 on 2022-08-24 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0025_auto_20220824_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeinformationattestation',
            old_name='or_code',
            new_name='qr_code',
        ),
    ]
