# Generated by Django 3.2.15 on 2022-08-28 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0026_rename_or_code_employeeinformationattestation_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
    ]
