# Generated by Django 3.2.15 on 2022-08-30 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_rename_member_name_users_employee_name'),
        ('employee_app', '0028_remove_employee_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographics',
            name='employee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demographics', to='admin_app.users'),
        ),
    ]
