from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('', views.LoginView.as_view(), name='login'),
                  path('create/employee/profile/<int:employee_id>/', views.CreateEmployeeProfile.as_view(),
                       name='index'),
                  path('create/employee/profile/W4/<int:employee_id>/', views.CreateEmployeeProfileW4.as_view(),
                       name='section_w4'),
                  path('create/employee/profile/withholding/allowance/certificate/<int:employee_id>/',
                       views.CreateEmployeeAllowanceCertificate.as_view(), name='allowance_certificate'),
                  path('create/employee/eligibility/verification/<int:employee_id>/',
                       views.EmployeeEligibilityVerification.as_view(), name='employee_eligibility_verification'),
                  path('create/employee/eligibility/verification/part/2/<int:employee_id>/',
                       views.EmployeeEligibilityVerificationPart2.as_view(),
                       name='employee_eligibility_verification_part_2'),
                  path('create/employee/personal/assistant/guide/page/6/<int:employee_id>/',
                       views.PersonalAssistantGuidePage6.as_view(),
                       name='personal_assistant_guide_page6'),
                  path('create/employee/voluntary/self/identification/page/7/<int:employee_id>/',
                       views.VoluntarySelfIdentificationPage7.as_view(),
                       name='voluntary_self_identification_page7'),
                  path('create/employee/authorization/background/check/page/8/<int:employee_id>/',
                       views.AuthorizationBackgroundCheckPage8.as_view(),
                       name='authorization_background_check_page8'),
                  path('create/employee/agreement/with/company/page/9/<int:employee_id>/',
                       views.AgreementWithCompanyPage9.as_view(),
                       name='agreement_with_company_page9'),
                  path('create/employee/drug/and/alcohol/testing/<int:employee_id>/',
                       views.DrugAndAlcoholTesting.as_view(),
                       name='drug_and_alcohol_testing'),
                  path('create/employee/notice/acknowledgement/page/10/<int:employee_id>/',
                       views.NoticeAcknowledgementPage10.as_view(),
                       name='notice_acknowledgement_page10'),
                  path('create/employee/benefit/portion/compensation/page/11/<int:employee_id>/',
                       views.BenefitPortionCompensationPage11.as_view(),
                       name='benefit_portion_compensation_page11'),
                  path('create/employee/deposit/authorization/page/12/<int:employee_id>/',
                       views.DepositAuthorizationPage12.as_view(),
                       name='deposit_authorization_page12'),
                  path('logout/', views.LogoutView.as_view(), name='logout'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
